# Generated by Django 4.1.3 on 2023-02-28 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=60, verbose_name='Nombre')),
                ('marca', models.CharField(default='', max_length=25, verbose_name='Marca')),
                ('modelo', models.CharField(default='', max_length=50, verbose_name='Modelo')),
                ('imagenes', models.ImageField(default='', upload_to='imagenes', verbose_name='Imagen/es')),
                ('precio', models.IntegerField(default=0, verbose_name='Precio')),
                ('proovedor', models.CharField(default='-', max_length=35, verbose_name='Proovedor')),
                ('capacidad', models.IntegerField(default=0, verbose_name='Capacidad')),
                ('cobertura', models.BooleanField(default=False, verbose_name='Tiene Cobertura:')),
                ('aire_acondicionado', models.BooleanField(default=False, verbose_name='Tiene Aire Acondicionado:')),
                ('kilometraje', models.BooleanField(default=False, verbose_name='Tiene Kilometraje:')),
                ('puertas', models.IntegerField(verbose_name='Cantidad de Puertas')),
                ('automatico', models.BooleanField(verbose_name='Transmision Automatica')),
                ('reservado', models.BooleanField(default=False, verbose_name='Esta reservado:')),
                ('lugarRetiro', models.CharField(default='', max_length=50, null=True, verbose_name='Lugar de Retiro')),
                ('fechaRetiro', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Retiro')),
                ('fechaRegreso', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Regreso')),
                ('idPayment', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID del pago')),
                ('userWhoPayed', models.CharField(blank=True, max_length=40, null=True, verbose_name='Comprador')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=40, verbose_name='Apellido')),
                ('dateBirth', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(max_length=40, verbose_name='Numero de Telefono')),
                ('doc_type', models.CharField(choices=[('dni', 'DNI'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=25, verbose_name='Tipo de Documento')),
                ('doc_number', models.CharField(max_length=40, verbose_name='Numero de Documento')),
                ('pais', models.CharField(choices=[('arg', 'Argentina'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=25, verbose_name='Pais')),
                ('provincia', models.CharField(choices=[('bsas', 'Buenos Aires'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=25, verbose_name='Provincia')),
                ('calle', models.CharField(max_length=20, verbose_name='Calle')),
                ('altura', models.CharField(blank=True, max_length=5, null=True, verbose_name='Altura')),
                ('ciudad', models.CharField(choices=[('bsas', 'Buenos Aires'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=25, verbose_name='Ciudad')),
                ('cp', models.CharField(max_length=7, verbose_name='Codigo Postal')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
