# Generated by Django 4.1.3 on 2023-01-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=60, verbose_name='Nombre')),
                ('marca', models.CharField(default='', max_length=25, verbose_name='Marca')),
                ('modelo', models.CharField(default='', max_length=50, verbose_name='Modelo')),
                ('imagenes', models.ImageField(default='', upload_to='', verbose_name='Imagen/es')),
                ('precio', models.IntegerField(default=0, verbose_name='Precio')),
                ('proovedor', models.CharField(default='-', max_length=35, verbose_name='Proovedor')),
                ('capacidad', models.IntegerField(default=0, verbose_name='Capacidad')),
                ('cobertura', models.BooleanField(default=False, verbose_name='Tiene Cobertura:')),
                ('aire_acondicionado', models.BooleanField(default=False, verbose_name='Tiene Aire Acondicionado:')),
                ('kilometraje', models.BooleanField(default=False, verbose_name='Tiene Kilometraje:')),
                ('reservado', models.BooleanField(default=False, verbose_name='Esta reservado:')),
                ('lugarRetiro', models.CharField(default='', max_length=50, verbose_name='Lugar de Retiro')),
                ('fechaRetiro', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Retiro')),
                ('fechaRegreso', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Regreso')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('nacimiento', models.DateField(verbose_name='Nacimiento')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('tipodocumento', models.CharField(max_length=15, verbose_name='Tipo DNI')),
                ('documento', models.IntegerField(verbose_name='Documento')),
                ('pais', models.CharField(max_length=40, verbose_name='Pais')),
                ('provincia', models.CharField(max_length=25, verbose_name='Provincia')),
                ('calle', models.CharField(max_length=40, verbose_name='Calle')),
                ('altura', models.CharField(max_length=20, verbose_name='Altura')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('cp', models.CharField(max_length=10, verbose_name='Codigo Postal')),
            ],
        ),
    ]
