# Generated by Django 4.1.5 on 2023-01-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('nacimiento', models.DateField(verbose_name='Nacimiento')),
                ('telefono', models.IntegerField(max_length=20, verbose_name='Telefono')),
                ('tipodocumento', models.CharField(max_length=15, verbose_name='Tipo DNI')),
                ('documento', models.IntegerField(max_length=35, verbose_name='Documento')),
                ('pais', models.CharField(max_length=40, verbose_name='Pais')),
                ('provincia', models.CharField(max_length=25, verbose_name='Provincia')),
                ('calle', models.CharField(max_length=40, verbose_name='Calle')),
                ('altura', models.CharField(max_length=20, verbose_name='Altura')),
                ('ciudad', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('cp', models.CharField(max_length=10, verbose_name='Codigo Postal')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origenVuelo', models.CharField(max_length=30, verbose_name='Origen')),
                ('destinoVuelo', models.CharField(max_length=30, verbose_name='Destino')),
                ('fechaIngreso', models.DateField(verbose_name='Ingreso')),
                ('fechaEgreso', models.DateField(verbose_name='Egreso')),
                ('opcionVuelo', models.CharField(max_length=15, verbose_name='Opciones')),
                ('cantidadPersonas', models.IntegerField(verbose_name='Cantidad')),
            ],
        ),
    ]
