# Generated by Django 4.1.3 on 2023-01-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='imagenes',
            field=models.ImageField(default='', upload_to='imagenes', verbose_name='Imagen/es'),
        ),
    ]
