# Generated by Django 4.1.3 on 2023-02-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_alter_auto_imagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='automatico',
            field=models.BooleanField(default=1, verbose_name='Transmision Automatica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auto',
            name='puertas',
            field=models.IntegerField(default=1, verbose_name='Cantidad de Puertas'),
            preserve_default=False,
        ),
    ]
