# Generated by Django 4.1.3 on 2023-02-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_auto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Status del pago'),
        ),
    ]
