# Generated by Django 4.1.3 on 2023-02-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_auto_automatico_auto_puertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='idPayment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID del pago'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='lugarRetiro',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='Lugar de Retiro'),
        ),
    ]
